name: Gaurav Sinha
description: Personal website
menu:
 - page: Profile
   url: /index
 - page: Publications
   url: /publications
 - page: Projects
   url: /projects
 - page: Contact
   url: /contact
mathjax: false
markdown: kramdown
encoding: utf-8
baseurl:
locale: en_GB
